title: Stavanger Oilers Boys 2016 hockey team
description: The homepage of the Stavanger Oilers 2016 boys hockey team
theme: just-the-docs

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
      values:
      layout: "default"

url: "https://g2016oilers.github.io"
repository: just-the-docs/just-the-docs # for github-metadata

title: Just the Docs
description: A Jekyll theme for documentation
baseurl: "/docs" # the subpath of your site, e.g. /blog
repository: just-the-docs/just-the-docs # for github-metadata

permalink: pretty

